(load "/Users/ryan/quicklisp/local-projects/cs325/bst.lisp")

(defun bst-elements (bst)
  (cond ((null bst) nil)
        ((null (node-l bst))
         (if (null (node-r bst))
              (list (node-elt bst))
            (reverse (cons (node-elt bst)
                           (reverse (bst-elements (node-r bst)))))))
        ((null (node-r bst))
         (cons (node-elt bst) (bst-elements (node-l bst))))
        (t (append (bst-elements (node-r bst))
                   (list (node-elt bst))
                   (bst-elements (node-l bst))))))